//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement_Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int DestinationId { get; set; }
        public string DestinationName { get; set; }
    }
}
