//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement_Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetails
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
