//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement_Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ItemDetails = new HashSet<ItemDetails>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Cgst { get; set; }
        public Nullable<decimal> Sgst { get; set; }
        public Nullable<decimal> PaybleAmount { get; set; }
        public Nullable<decimal> NetPaybleAmount { get; set; }
        public string PromoCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDetails> ItemDetails { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
